services:
  postgres:
    image: postgres:15.3
    container_name: postgres-ss
    environment:
      POSTGRES_DB: ss
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'