services:
  postgres:
    image: postgres:15.3
    container_name: postgres-ss
    environment:
      POSTGRES_DB: ss
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
  app:
    build: .
    container_name: ss-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ss
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - postgres