spring:
  application:
    name: ski-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ss}
    password: ${DB_PASSWORD:pass}
    username: ${DB_USERNAME:user}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: ${IN_CLAUSE_PARAMETER_PADDING:true}
        show_sql: false
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-ss-master.xml
    enabled: true
    default-schema: ss

app:
  rental:
    item:
      count-equipment-per-rental-order: ${COUNT_EQUIPMENT_PER_RENTAL_ORDER:3}


security:
    secret: ${SECURITY_SECRET:4f8a9c2b3d1e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a}